AlexvZyl/nordic.nvim

lua/nordic/colors.lua, lua/nordic/groups/native/editor.lua
=> fix(diff): fix diff foreground color

lua/nordic/groups/integrations/treesitter.lua
Hey, I've been playing around with the colorscheme and some code I had and it seems like `html` files does not have highlighting at all when using the treesitter parser so I've added some missing highlighting groups to fix that behavior and also some life quality improvements for markup languages (adding more `@text` groups) :p
HTML files before:
HTML files after:
=> feat: add some missing treesitter hl groups

lua/nordic/groups/integrations/treesitter.lua
seems like i somehow accidentally removed the `fg =` part of the `@tag.attribute` definition while pushing before :/
=> fix(treesitter): fix `@tag.attribute` definition

README.md, lua/nordic/colors/init.lua, lua/nordic/config.lua, lua/nordic/tests/options.lua
I propose using a more dim color for FloatBorder so it does not distract an eye from the contents of a floating window.
Before:
After:
Before:
After:
=> Feat: Border brightness

platforms/fish/Nordic.theme
=> feat(platforms): add support for fish shell

lua/nordic/groups/init.lua, lua/nordic/groups/integrations/ministatusline.lua
Hello! 👋🏻   I'd like to support `mini.statusline`.
- Colors are based on current `lualine` integration
- https://github.com/AlexvZyl/nordic.nvim/blob/main/lua/lualine/themes/nordic.lua
- Highlight groups for `mini.statusline`
- https://github.com/echasnovski/mini.statusline/blob/main/lua/mini/statusline.lua#L44-L63
(This is my first time contributing to a Lua project, so please let me know if I missed something. 😅 )
=> Support mini.statusline

lua/nordic/utils.lua
Discussed in #48, introduced in #97.  
Why did the tests not catch it?
=> Fix(utils): Handle case where we try to blend 'NONE'

lua/nordic/groups/integrations/nvim-cmp.lua
=> Fix: broken highlight link

.github/workflows/tests.yml, lua/nordic/colors/init.lua, lua/nordic/colors/nordic.lua, lua/nordic/groups/init.lua, lua/nordic/groups/integrations.lua, lua/nordic/groups/native.lua, lua/nordic/init.lua
This PR improves the handling of state and config loading.
=> Fix state/config loading, test on all PRs and add use case

lua/nordic/colors/init.lua, lua/nordic/init.lua
Currently on_palette can irreversibly change the palette requiring a full restart to fix.
This also means that implementations of on_palette have to account for changes made in previous calls.
This commit fixes that by rebuilding the palette with each setup.
As such extend_palette has been renamed to build_palette.
=> feat(colors): make on_palette stateless;

lua/nordic/colors/init.lua
I changed to `bg_popup = bg_float` and `bg_selected = gray2`:
& with `swap_background = true`:
The other thing I think looks better is changing `bg_visual = gray2` here it is with blend set to `0.5`:
- old:
- new:
Closes #135
=>  Feat: Improve pmenu & bg_visual colors for better visibility

README.md, lua/nordic/colors/init.lua, lua/nordic/config.lua, lua/nordic/utils.lua
So somehow I missed that `C = vim.deepcopy(P)` (#125 ) would break the upvalue reference, then somehow I did not notice that while testing (If I did any testing, that is, I don't really remember...).
Anyway, this should fix that, and it's more readable now.
Super-Duper, sorry about this (´°ω°`)
=> fix(build_palette): fix broken reload in stateless palette;

README.md, lua/nordic/colors/init.lua, lua/nordic/compatibility.lua, lua/nordic/config.lua, lua/nordic/groups/init.lua, lua/nordic/tests/options.lua
`override` configuration option replaced with `on_highlight` similar to tokyonight's [on_highlights](https://github.com/folke/tokyonight.nvim/blob/fbe3a27378fdd51a8ddd04f57012455436916a62/lua/tokyonight/theme.lua#L873):
```lua
require 'nordic' .setup {
-- This callback can be used to override highlights before they are applied.
on_highlight = function(highlights, palette)
highlights.TelescopePromptTitle = {
fg = palette.red.bright,
bg = palette.green.base,
italic = true,
underline = true,
sp = palette.yellow.dim,
undercurl = false
}
end
}
```
=> Feat: Improve changing of highlights with `on_highlight`

lua/nordic/groups/integrations.lua
Added highlighting for the rainbow-delimiters plugin (https://github.com/HiPhish/rainbow-delimiters.nvim)
Just added the highlighting to the integrations page. Used the colors I thought looked best in the context of the colorscheme
=> added support for rainbow-delimeters.nvim

lua/nordic/groups/integrations.lua
Fixes: #151 
**NeoTreeFileName** was linked to **NvimTreeNormal** which has a bg specified that bg was overwriting the selection highlighting:
There are two ways this is can be fix:
1. `G.NeoTreeFileName = { fg = C.fg }`
2. Just remove the whole thing... It defaults to the normal foreground so I went with this. (Also that's what every other theme I looked at did).
=> Fix: Weird neo-tree highlights;

.github/workflows/tests.yml, .stylua.toml, README.md, doc/nordic.nvim.txt, lua/lualine/themes/nordic.lua, lua/nordic/colors/init.lua, lua/nordic/colors/nordic.lua, lua/nordic/compatibility.lua, lua/nordic/config.lua, lua/nordic/groups/init.lua, lua/nordic/groups/integrations.lua, lua/nordic/groups/native.lua, lua/nordic/groups/terminal.lua, lua/nordic/init.lua, lua/nordic/tests/init.lua, lua/nordic/tests/options.lua, lua/nordic/tests/utils.lua, lua/nordic/utils.lua
Closes #156
Closes #140
Closes #135 
Closes #126 
Closes #121 
Closes #100
=> Release 0.1.0

lua/nordic/colors/init.lua, lua/nordic/colors/nordic.lua, platforms/ghostty/README.md, platforms/ghostty/nordic
Add Ghostty colors and configuration as well as a very short readme to explain how to set it up.
=> Add support for Ghostty terminal emulator

lua/nordic/groups/integrations.lua
=> Common tree highlight groups

.github/workflows/tests.yml
Upstream changed the path to the neovim appimage and since we no longer need the nightly version of neovim, we can use the latest release.
Also update checkout action to v4.
=> ci(tests): fix path to neovim appimage

lua/nordic/config.lua, lua/nordic/groups/integrations/visual_whitespace.lua
Provides integration with the [visual-whitespace.nvim plugin](https://github.com/mcauley-penney/visual-whitespace.nvim). It's a plugin to show whitespace in visual mode, similar to how it works with trailing whitespace when setting [`listchars`](https://neovim.io/doc/user/options.html#'listchars').
Example of how it looks:
=> Integration with visual-whitespace.nvim
